name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경: 최신 Ubuntu

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3  # GitHub 저장소를 체크아웃

      - name: Ruby & Jekyll 설치
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3.7'  # 사용할 Ruby 버전 (Jekyll은 Ruby 기반)

      - name: Bundler 및 Jekyll 설치
        run: |
          gem install bundler
          bundle install --gemfile=docs/Gemfile  # docs 폴더의 Gemfile을 사용하도록 설정

      - name: Jekyll 사이트 빌드
        run: bundle exec jekyll build --source docs --destination _site  # docs 폴더를 기준으로 빌드

      - name: GitHub Pages에 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # 빌드된 사이트가 _site 폴더에 저장됨
